[set] volume <number>: user.newapi.media.set_volume(number)
volume up: key(volup)
volume down: key(voldown)
volume (mute | unmute): key(mute)
play track: key(play)
pause track: key(pause)
(next | neck) track: key(next)
(last | larse) track: key(prev)
