web search <user.dictation>$:   user.web_search(dictation)
google <user.dictation>$:       user.google_search(dictation)
bing search <user.dictation>$:  user.bing_search(dictation)
duck duck go <user.dictation>$: user.duckduckgo_search(dictation)
amazon <user.dictation>$:       user.amazon_search(dictation)
youtube <user.dictation>$:      user.youtube_search(dictation)
(wikipedia | wiki) <user.dictation>$: user.wikipedia_search(dictation)
