(minimize | mini): app.window_hide()
(maximize | maxi): user.maximize()
quit program: app.window_close()
(next | neck) (window | win): app.window_next()
(last | larse) (window | win): app.window_previous()
(new | open) (window | win): app.window_open()
[show] programs: user.all_programs()
fullscreen: user.toggle_fullscreen()
