minimize: app.window_hide()
maximize: user.maximize()
quit program: app.window_close()
(next | neck) (window | win): app.window_next()
(last | larse) (window | win): app.window_previous()
(new | open) (window | win): app.window_open()
[show] programs: user.all_programs()
fullscreen: user.toggle_fullscreen()

align {user.window_align_position}: user.align_window(window_align_position)
